"""Deterministic safety guardrails for the intelligent agent."""

from .budget import (
    CALL_BUDGET_EVENT_CODE,
    CallBudgetConfig,
    call_budget_triggered,
    load_call_budget_config,
    prepare_model_call,
)
from .events import (
    FAIL_SOFT_NOTE,
    FAIL_SOFT_RESPONSE,
    build_fail_soft_message,
    build_guardrail_trace_attributes,
    count_safe_tool_errors,
)
from .loop_detector import (
    LOOP_DETECTED_EVENT_CODE,
    TOOL_CALL_FINGERPRINT_ERROR_CODE,
    LoopDetectionConfig,
    LoopDetectionResult,
    ToolCallFingerprint,
    canonicalize_tool_arguments,
    detect_duplicate_tool_calls,
    fingerprint_tool_call,
    load_loop_detection_config,
)
from .relevance import (
    DEFAULT_OFF_TOPIC_PATTERNS,
    DEFAULT_WINE_TOPIC_ALLOWLIST,
    RELEVANCE_DEFLECTED_EVENT_CODE,
    RELEVANCE_REDIRECT,
    RelevanceConfig,
    RelevanceDecision,
    evaluate_relevance,
    load_relevance_config,
    normalize_relevance_text,
    relevance_was_deflected,
)
from .safe_errors import (
    SafeToolError,
    SafeToolErrorCode,
    build_safe_tool_call_wrapper,
    format_safe_tool_error,
    get_safe_tool_error,
)
from .sanitizer import (
    REDACTION_TOKEN,
    SanitizationResult,
    SensitiveOutputSanitizer,
)

__all__ = [
    "CALL_BUDGET_EVENT_CODE",
    "CallBudgetConfig",
    "DEFAULT_OFF_TOPIC_PATTERNS",
    "DEFAULT_WINE_TOPIC_ALLOWLIST",
    "FAIL_SOFT_NOTE",
    "FAIL_SOFT_RESPONSE",
    "LOOP_DETECTED_EVENT_CODE",
    "TOOL_CALL_FINGERPRINT_ERROR_CODE",
    "LoopDetectionConfig",
    "LoopDetectionResult",
    "RelevanceConfig",
    "RelevanceDecision",
    "RELEVANCE_DEFLECTED_EVENT_CODE",
    "RELEVANCE_REDIRECT",
    "SafeToolError",
    "SafeToolErrorCode",
    "SanitizationResult",
    "SensitiveOutputSanitizer",
    "ToolCallFingerprint",
    "REDACTION_TOKEN",
    "build_safe_tool_call_wrapper",
    "build_fail_soft_message",
    "build_guardrail_trace_attributes",
    "call_budget_triggered",
    "canonicalize_tool_arguments",
    "count_safe_tool_errors",
    "detect_duplicate_tool_calls",
    "evaluate_relevance",
    "fingerprint_tool_call",
    "format_safe_tool_error",
    "get_safe_tool_error",
    "load_call_budget_config",
    "load_loop_detection_config",
    "load_relevance_config",
    "normalize_relevance_text",
    "prepare_model_call",
    "relevance_was_deflected",
]
